#!/bin/env bash
bash /opt/jd/jd.sh jd_bean_change now
bash /opt/jd/jd.sh jd_bean_home now
bash /opt/jd/jd.sh jd_bean_sign now
bash /opt/jd/jd.sh jd_beauty now
bash /opt/jd/jd.sh jd_big_winner now
bash /opt/jd/jd.sh jd_blueCoin now
bash /opt/jd/jd.sh jd_bookshop now
bash /opt/jd/jd.sh jd_car_exchange now
bash /opt/jd/jd.sh jd_car now
bash /opt/jd/jd.sh jd_carnivalcity now
bash /opt/jd/jd.sh jd_cash now
bash /opt/jd/jd.sh jd_cfd now
bash /opt/jd/jd.sh jd_club_lottery now
bash /opt/jd/jd.sh jd_crazy_joy_bonus now
bash /opt/jd/jd.sh jd_crazy_joy now
bash /opt/jd/jd.sh jd_daily_egg now
bash /opt/jd/jd.sh jd_daily_lottery now
bash /opt/jd/jd.sh jd_dreamFactory now
bash /opt/jd/jd.sh jd_fruit now
bash /opt/jd/jd.sh jd_get_share_code now
bash /opt/jd/jd.sh jd_gold_creator now
bash /opt/jd/jd.sh jd_health_collect now
bash /opt/jd/jd.sh jd_health now
bash /opt/jd/jd.sh jd_jdfactory now
bash /opt/jd/jd.sh jd_jdzz now
bash /opt/jd/jd.sh jd_jin_tie now
bash /opt/jd/jd.sh jd_joy_feedPets now
bash /opt/jd/jd.sh jd_joy_help now
bash /opt/jd/jd.sh jd_joy now
bash /opt/jd/jd.sh jd_joy_reward now
bash /opt/jd/jd.sh jd_joy_run now
bash /opt/jd/jd.sh jd_joy_steal now
bash /opt/jd/jd.sh jd_jump now
bash /opt/jd/jd.sh jd_jxlhb now
bash /opt/jd/jd.sh jd_jxmc now
bash /opt/jd/jd.sh jd_jxnc now
bash /opt/jd/jd.sh jd_kd now
bash /opt/jd/jd.sh jd_live now
bash /opt/jd/jd.sh jd_live_redrain now
bash /opt/jd/jd.sh jd_lotteryMachine now
bash /opt/jd/jd.sh jd_market_lottery now
bash /opt/jd/jd.sh jd_mcxhd now
bash /opt/jd/jd.sh jd_mohe now
bash /opt/jd/jd.sh jd_moneyTree now
bash /opt/jd/jd.sh jd_ms now
bash /opt/jd/jd.sh jd_necklace now
bash /opt/jd/jd.sh jd_nzmh now
bash /opt/jd/jd.sh jd_pet now
bash /opt/jd/jd.sh jd_pigPet now
bash /opt/jd/jd.sh jd_plantBean now
bash /opt/jd/jd.sh jd_price now
bash /opt/jd/jd.sh jd_rankingList now
bash /opt/jd/jd.sh jd_redPacket now
bash /opt/jd/jd.sh jd_sgmh now
bash /opt/jd/jd.sh jd_shop now
bash /opt/jd/jd.sh jd_small_home now
bash /opt/jd/jd.sh jd_speed now
bash /opt/jd/jd.sh jd_speed_redpocke now
bash /opt/jd/jd.sh jd_speed_sign now
bash /opt/jd/jd.sh jd_star_shop now
bash /opt/jd/jd.sh jd_superMarket now
bash /opt/jd/jd.sh jd_syj now
bash /opt/jd/jd.sh jd_unsubscribe now
bash /opt/jd/jd.sh jd_xtg_help now
bash /opt/jd/jd.sh jd_xtg now
bash /opt/jd/jd.sh jd_zooCollect now
bash /opt/jd/jd.sh jd_zoo now
bash /opt/jd/jd.sh jd_crazy_joy_coin now
